name: Auth & Security Settings
before: |
  <p>
    Arkime applications have common authorization and security settings.
  </p>
  <p>
    These settings should live in the <code>[cont3xt]</code>, <code>[parliament]</code>, <code>[wiseService]</code> or <code>[default]</code> sections depending on the Arkime application.
  </p>

settings:
  - key: dropGroup
    value: EMPTY
    text: |
      Group to drop privileges to. The <a href="#pcapDir">pcapDir</a> must be writable by this
      group or to the user specified by dropUser

  - key: dropUser
    value: EMPTY
    text: |
      User to drop privileges to. The <a href="#pcapDir">pcapDir</a> must be writable by this
      user or to the group specified by dropGroup

  - key: httpRealm
    value: Moloch
    text: |
      HTTP Digest Realm - Used by digest mode AND for encoding user passwords.
      Changing the value will cause all previous stored passwords to no longer work.

  - key: serverSecret
    value: 'Value of <a href="#passwordSecret">passwordSecret</a>'
    text: |
      The server-to-server shared key. All viewers in the Arkime cluster must have the same value.
      It should be changed periodically.

  - key: authMode
    value: EMPTY
    text: |
      (Since 5.0.0) This setting controls what authentication mode is used, if authMode or userNameHeader isn't set then digest is used by default. Before Arkime 5 <a href="#userNameHeader">userNameHeader</a> is used to select the auth mode.
      Possible values are:
      <ul>
        <li><strong>basic</strong> - Use basic auth where browser based basic authentication is used.</li>
        <li><strong>basic+oidc</strong> - Use basic auth when present otherwise use oidc auth. This is useful when you want to support API calls using basic auth. WARNING - the password for basic auth is from Arkime which isn't synced with oidc.</li>
        <li><strong>basic+form</strong> - Use basic auth when present otherwise use form auth. This is useful when you want to support API calls using basic auth.</li>
        <li><strong>digest</strong> or EMPTY - Use digest auth where browser based digest authentication is used.</li>
        <li><strong>form</strong> - Use a html form to enter the user/password. Using over http is insecure.</li>
        <li><strong>header</strong> - Use a http header containing the user id for authentication, see <a href="#userNameHeader">userNameHeader</a>.</li>
        <li><strong>oidc</strong> -  Use OIDC authentication.</li>
        <li><strong>anonymous</strong> - Use anonymous authentication, not recommended.</li>
        <li><strong>s2s</strong> -  Only server to server authentication is allowed</li>
      </ul>
      If using central viewers for maximum security set all viewers to use s2s except the central viewer.
      Each user must have Web Auth Header checkbox set to support other methods besides basic or digest.
      <br><br>
      For authentication modes that require cookies (form, oidc, saml) you may need to also change:
      <ul>
        <li> <a href="#authCookieSecure">authCookieSecure</a> - Set to <b>false</b> if using http WITHOUT a reverse proxy. This is insecure.</li>
        <li> <a href="#authTrustProxy">authTrustProxy</a> - Set to <b>true</b> if using http WITH a https reverse proxy.</li>
      </ul>
      See the <a href="#logoutUrl">logoutUrl</a> setting for how to configure a logout button in the UI.

  - key: userNameHeader
    value: EMPTY
    text: |
      If using Arkime 5 or later please use <a href="#authMode">authMode</a> to select the auth mode and only use userNameHeader in header auth mode.
      Arkime 6 will no longer support this setting, except for the header name.
      Before Arkime 5 this setting controls what auth mode is used OR what header to user when using header auth.
      Possible values are:
      <ul>
        <li><strong>digest</strong> - Run in digest mode where browser based authentication is used.</li>
        <li><strong>oidc</strong> - (Since 4.2.0) Use OIDC authentication.</li>
        <li><strong>anonymous</strong> - (Since 4.2.0) Use anonymous authentication.</li>
        <li><strong>s2s</strong> - (Since 4.2.0) Only server to server authentication is allowed</li>
        <li>Any other value - The lowercase http header key to use for determining the user id.
            It is recommended you set viewHost to localhost when using this setting, or use iptables, otherwise a hacker can just send this header.
        </li>
      </ul>
      If using central viewers for maximum security set all viewers to use s2s except the central viewer.
      Each user must have Web Auth Header checkbox set to support other methods besides digest.

  - key: requiredAuthHeader
    value: EMPTY
    text: |
      Used for allowing an external system like LDAP or Active Directory to
      manage user provisioning and activation/deactivation.  It is assumed that the
      header contains a list of user roles (like active directory groups)
      which are inspected against the value in <code>requiredAuthHeaderVal</code> (see below)
      to verify that the user is in the appropriate group (ie. "ArkimeUsers").  If
      so, the user is authorized to use the system, and if an account does not
      already exist for them in the Arkime user store,
      it is created (see <code>userAutoCreateTmpl</code>)

  - key: requiredAuthHeaderVal
    value: EMPTY
    text: |
      A value (or comma seperated list of possible values since 5.3.0) that the header <a href="#requiredAuthHeader">requiredAuthHeader</a> is matched against.
      If the header contains one of the values, the user is authorized to use the system otherwise they will be denied.

      For example
      <pre>requiredAuthHeader=company-x-role
      requiredAuthHeaderVal=arkime,admin
      </pre>
      a user with a header of <code>company-x-role: foo,arkime,office</code> or <code>company-x-role: foo,admin,bar</code> would
      be authorized, while a user with a header of <code>company-x-role: foo,office</code> would not be authorized.

  - key: userAutoCreateTmpl
    value: EMPTY
    text: |
      <p>
      When using <code>requiredAuthHeader</code> to externalize provisioning
      of users to a system like LDAP/AD, this configuration parameter is used
      to define the JSON structure used to automatically create a Arkime user
      in the Arkime users database if one does not exist.  The user will only
      be created if the <code>requiredAuthHeader</code> includes the expected
      value in <code>requiredAuthHeaderVal</code>, and is not automatically deleted
      if the auth headers are not present.  Values can be populated into
      the creation JSON to dynamically populate fields into the user database,
      which are passed in as HTTP headers along with the user and auth headers.
      The example value below creates a user with a userId pulled from the
      <code>http_auth_http_user</code> HTTP header with a name pulled from
      the <code>http_auth_mail</code> user header.  It is expected that these
      headers are passed in from an apache (or similar) instance that fronts
      the Arkime viewer as described in the documentation supporting <code>userNameHeader</code>
      <code>
        {"userId": "${this.http_auth_http_user}", "userName": "${this.http_auth_mail}",
        "enabled": true, "webEnabled": true, "headerAuthEnabled": true,
        "emailSearch": true, "createEnabled": false, "removeEnabled": false, "packetSearch": true,
        "roles": ["arkimeUser", "cont3xtUser"]}
      </code>
      </p>
      <p>
        <strong>Note:</strong> Using a dash (<code>-</code>) in the header name requires special care since Javascript treats as subtraction.
        For example with <code>"userId": "$(this.user-id)"</code> Javascript sees as <code>this.user - id</code>.
        Instead you will need to use <code>"userId": "$(this[\\"user-id\\"])"</code> if you can't switch to a different variable name.
      </p>

  - key: caTrustFile
    value: EMPTY
    text: |
      Optional file with PEM encoded certificates to use when validating certs. Make sure to read this <a href="faq#self-signed-ssl-tls-certificates">FAQ entry.</a>

  - key: userAuthIps
    value: "For header auth 127.0.0.0/8 and ::1, otherwise all ips"
    text: |
      (Since 3.4.0) A comma separated list of ips allowed to be used for authenticated calls, no error checking is done on the ips.

  - key: authTrustProxy
    value: EMPTY
    text: |
      (Since 5.0.0) Used to set the express "trust proxy" setting that might be needed if viewer is running in http mode and a reverse proxy is being used in https mode.
      Please <a href="https://expressjs.com/en/guide/behind-proxies.html">read more</a> about the setting and possible values.

  - key: authCookieSecure
    value: true
    text: |
      (Since 5.0.0) This setting controls if authentication cookies are marked as "secure".
      If using cookie based auth (form, oidc, saml) over http change this to false.

  - key: authCookieSameSite
    value: 'Lax'
    text: |
      (Since 5.0.0) For auth cookies (form, oidc, saml) what value is used for sameSite.

  - key: logoutUrl
    value: Only set for form authMode
    text: |
      (Since 5.0.0) When set Arkime will show a logout button in the UI that will redirect to this url.
      For "form" authMode, Arkime provides a web page to logout.
      All other authMode requires this setting to be set, or no logout button will be shown.
      Note, "basic" and "digest" authMode do not support logout in most browsers and "oidc" authMode will require an url from the OIDC provier.

  - key: loginMessage
    value: EMPTY
    text: An optional login message to present on the login page when using authMode=form
